apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/instance: smb-general
resources:
- sealed-config.yaml
- sealed-creds-smb.yaml
- generated.yaml
- storageclass.yaml
