apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: democratic-csi
namespace: democratic-csi
resources:
- namespace.yaml
- iscsi-general
- smb-general
- node-manual-general

images:
- name: ghcr.io/democratic-csi/democratic-csi
  newTag: v1.9.5
