apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: democratic-csi
namespace: democratic-csi
resources:
- namespace.yaml
- iscsi-general
