apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: democratic-csi
namespace: democratic-csi
resources:
- namespace.yaml
- iscsi-general

images:
- name: docker.io/democraticcsi/democratic-csi
  tag: next
  digest: sha256:5b607d63a270330b4cdaa70ae961fc1484f0dda3d164d940e69e1faa213682fd
