apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: invidious
spec:
  destinations:
  - namespace: "invidious"
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: invidious
spec:
  project: invidious
  source:
    path: kubernetes/invidious
  destination:
    namespace: invidious
