---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-smb-manual
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: node-manual-general
    readOnly: false
    fsType: cifs
    volumeHandle: plex-media-smb-manual
    nodeStageSecretRef:
      name: creds-smb-general
      namespace: democratic-csi
    volumeAttributes:
      server: truenas.lab.yuha0.com
      share: media
      node_attach_driver: smb
      provisioner_driver: node-manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-smb-manual
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
