apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/instance: iscsi-general
resources:
- sealed-config.yaml
- sealed-chap.yaml
- generated.yaml
- storageclass.yaml
