apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: truenas-tls-certificate
spec:
  dnsNames:
  - truenas.lab.yuha0.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  secretName: truenas-tls-certificate
