apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: metrics
resources:
- deployment.yaml
- service.yaml
- servicemonitor.yaml
configMapGenerator:
- name: graphite-config
  files:
  # https://raw.githubusercontent.com/Supporterino/truenas-graphite-to-prometheus/refs/tags/v2.2.1/graphite_mapping.conf
  - graphite_mapping.conf
