---

apiVersion: v1
kind: Service
metadata:
  name: graphite-exporter-metrics
spec:
  ports:
  - name: metrics
    targetPort: metrics
    port: 9108
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: graphite-exporter-receive
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 10.200.0.5
  type: LoadBalancer
  ports:
  - name: receive
    targetPort: receive
    port: 9109
    protocol: TCP
