---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tailscale-auth
  namespace: tailscale
spec:
  encryptedData:
    AUTH_KEY: AgAz8KdKCx9QIcPY3396f+C/J0cDoi/63VIaG2Uj88aAoaZn29IbY9bH2aE+qGouFH7dFchYOVIql0jyOwEIKwp0DM9X1oRfsOl8O70C6KbL+oF3xLcijx9agqIq9QL+2yYiD3naaBkVUVL+kMx4d1f/7gTyGJGeDH92qVgsUWl3pdVYZ2cucvfM+GfZLvh+OOlEu+yPOhR3yUvuHZ42lvrpUxC70Li7BqtY9MQL1FQ9Xo9ZN8ck7C5sepsvV1eVKLqSQobIL+TFALr2AEzlTl6ya3tJoLmmiYoSW+fcmg9MuLXHEdmxu0931DmhotSYorDC+1j4tsmI0N7ESwrDKgDX0PboOVQVTt4jsrCS2dhfNF8DHpLnzK/Rp2ygM6+52YzBYPtXAo+l7fGI9bSNgkWAFYDbCwgmgrjSMjw+zjv7WSUtQRNe9JnC3AgQSwSxsPPZUm2KwEkJUUiiGfgTnO3216dadIW/jqDus5ReUlwyRPvlAh/WGBkjYDsLa6DBqzYyuqJi4LjzSESpfqVplIT0mq9imvbKvhMzn+PyHzRzj5LIM4UrYaK6CT3xGGMXBg79xlSAbQ4a1sxKcKpsrbd2T/Zkh5sxZaIZTAKf3+2f4xDE1xuvbBXD2+hkKD48C/jOpIqy9nO/v2r3KNVTN2DZ0ivmVX9HNRx+yHNdMjyv3A33APQ83ltlm0YvHS3Sg2QMRorXgEotY6s4PCf8yRPmCZ6Uk05nsjG1eDstohvqOrJGRwjXMb6B3WV6xDuaMWMllvjzr5IXADGREQqq
  template:
    metadata:
      creationTimestamp: null
      name: tailscale-auth
      namespace: tailscale
    type: Opaque
