---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: seaweedfs-admin
  namespace: seaweedfs
spec:
  encryptedData:
    adminPassword: AgBwzuTM/zJkNcSHAeXeUMsJdCBZ6i4pHVXKRY0q+YQx89XF2f8N+YOA74e0KEQ3gWNVofu/W9pq9vNVnPworYGbBfzmabI65/DxlOCKLCt6+S7FsKJOExONia2CWhMNX6yhq4CN8vDdLzaHUoBrMoDEVAA1OlY0Sd4WoZBQWI0ctfsYdwDAiWzKCF/RGWAdDargVdJxFUYPqkvYb/G97+7hA5RymDFKfzHK94sYq4/oY3MMCrjF0Y56xEfwjG9Z3FElZe9KZobYGN7OMUC5QgPDrOgLJsXf/emrHJ/pahGaYm9qeh1F30BLvFm1mxFivEArKVuHuIVoZVnVldFivsFMA6lzkhiS3jKNhgPvH6Mj5mgxwIgq1xY+YC22XA4/M3lMD/tENQ06/Kek8UFSuhgRU3SAk1fexWUs77vsDZ3a6hAGgHhRH4XX+APAe7m0KMu2qE7jGFQ2OycHVTeSqmfJGPsb5Je/UMHGi/coNsDe4baljYh2wQ7qgZHUmUf6ut/wxHEJ2ZXZ0Z+N5zQ/le2XwUiOfbltytfrltMDFDk/QVKTbe5Qt16EijpcJkBXt/0LvUkMxoaHqSj/yhSxaGUtqL3YNBdd3u6/NidSJAZUfTQD20UsmwtPXv6OcjZL7S1qE3wgSFi7rcVcW24LT16vdjtCeKVO73z1na/oACUmPAu6A95RUfVnwbhmQ7CHbqVw1f8xk36WtEc0rqsDxGRcdcGwymzWcGJp+E8S+vY=
    adminUser: AgAQDBAUnH5WFNCIYcn4bnPyevUAgQ7QqstpnkFke+soP6BV6d+hoM3FIWh2HQtEKbHItMhl+fW4n06Bu0ed19/ryUrOJfPwTcU8YfIYZ3J2rgR+8ItPqOHFAphbgevuL9olmBquhGjiqSxyD/fzg/Uzx0RxxoAHR6rZbBmKhOg9h+aegdr4ZUP8TyJ7xq7ENxYTAvirzc9S5QNF3D0JdB3PtL4AqpGwme0+d+IPbOiCXlfqd5l38Qkd4xOc1UPQJQjwyRiC/liWcJIgqUPQKEjru6/Q6FinjhktE+1X6y2PJNtqDfu71lG1z2u21HspEpCrZjhoNQU9hontdhsHT6vGep35gLUEnrD/CP5QocUcrzyyeY1ROtBNwO/80U9kiB+pL/uFzrvEyCmKR4khhztuVeX1+8sLXA3hRs8ICFe5pX4mFjESP5bszCZR72jzEtfld9Q+lJOdIzK77/k8xcn2qsQ4I9P1SqCHbvEtTlMrfLQvuJujxUYNfmAikI/ct6yMrucUsPk75fJaY05XFODJ97cuqGLQtuXSsz4pX1LvZg7MIj9GGbfdywUbkphQVjPf8VfQdbuf+5ZOWFlxHGOAzibDe3zOofKdF8cwGqSkT6Edh1T+4GCO+iFlWV26zjetxOfJnlY6aDU4uks7UTdFMdWNN9p3XhfE0aKXHbGdxEkEKlathxxSOyHUwE+UesNotIpxGA==
  template:
    metadata:
      creationTimestamp: null
      name: seaweedfs-admin
      namespace: seaweedfs
    type: Opaque
